# Generated by Django 5.2.1 on 2025-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cuenta_unam', models.CharField(blank=True, max_length=20, verbose_name='No. Cuenta/Empleado')),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('tipo_curso', models.CharField(max_length=12)),
                ('nivel_ingreso', models.CharField(max_length=10)),
                ('idioma', models.CharField(max_length=20)),
                ('horario', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
