# Generated by Django 5.2.1 on 2025-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
