# Generated by Django 5.2.1 on 2025-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_inscripcion_fecha_fin_inscripcion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
