# Generated by Django 5.2.1 on 2025-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_examencolocacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('cuenta_unam', models.CharField(max_length=20, verbose_name='No. de Cuenta/UNAM')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('idioma', models.CharField(choices=[('ingles', 'Inglés'), ('frances', 'Francés'), ('aleman', 'Alemán'), ('italiano', 'Italiano'), ('portugues', 'Portugués'), ('japones', 'Japonés'), ('chino', 'Chino'), ('coreano', 'Coreano'), ('esp_extranjeros', 'Español para extranjeros'), ('otro', 'Otro')], max_length=30, verbose_name='Idioma')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
            ],
            options={
                'verbose_name': 'Registro Lista de Espera',
                'verbose_name_plural': 'Registros Lista de Espera',
                'ordering': ['-creado'],
            },
        ),
    ]
