# Generated by Django 5.2.1 on 2025-07-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_listaespera'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAgosto2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('cuenta_unam', models.CharField(blank=True, max_length=20, verbose_name='No. de Cuenta/UNAM')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('tipo_curso', models.CharField(max_length=30, verbose_name='Tipo de curso')),
                ('idioma', models.CharField(max_length=30, verbose_name='Idioma')),
                ('nivel_ingreso', models.CharField(max_length=30, verbose_name='Nivel de ingreso')),
                ('horario', models.CharField(max_length=50, verbose_name='Horario')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje (opcional)')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
            ],
            options={
                'verbose_name': 'Registro Agosto 2025',
                'verbose_name_plural': 'Registros Agosto 2025',
                'ordering': ['-creado'],
            },
        ),
    ]
