# Generated by Django 5.2.1 on 2025-07-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_registroagosto2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAgosto2025',
        ),
    ]
