# Generated by Django 5.2.1 on 2025-08-07 01:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_delete_registroagosto2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaespera',
            name='horario_deseado',
            field=models.CharField(blank=True, choices=[('por la mañana', 'Por la mañana'), ('a media tarde', 'A media tarde'), ('por la noche', 'Por la noche'), ('fin de semana', 'Fin de semana')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='nivel',
            field=models.CharField(blank=True, choices=[('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='cuenta_unam',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='idioma',
            field=models.CharField(choices=[('ingles', 'Inglés'), ('frances', 'Francés'), ('aleman', 'Alemán'), ('italiano', 'Italiano'), ('portugues', 'Portugués'), ('japones', 'Japonés'), ('chino', 'Chino'), ('coreano', 'Coreano'), ('esp_extranjeros', 'Español para extranjeros'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listaespera',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
